title: Lunar Linux
url: "https://lunar-linux.org"

email: info@lunar-linux.org

tagline: Lunar Linux is an advanced source-based distribution.

error_page:
  head: Page Not Found
  text: The requested page could not be found.

links:
  github:
    project: "https://github.com/lunar-linux"
    lunar: "https://github.com/lunar-linux/lunar-tools"
    theedge: "https://github.com/lunar-linux/lunar"
    moonbase:
      core: "https://github.com/lunar-linux/moonbase-core"
      xorg: "https://github.com/lunar-linux/moonbase-xorg"
      kde: "https://github.com/lunar-linux/moonbase-kde"
      gnome: "https://github.com/lunar-linux/moonbase-gnome"
      gnome3: "https://github.com/lunar-linux/moonbase-gnome3"
      xfce: "https://github.com/lunar-linux/moonbase-xfce"
      efl: "https://github.com/lunar-linux/moonbase-efl"
      other: "https://github.com/lunar-linux/moonbase-other"
    iso: "https://github.com/lunar-linux/lunar-iso"

#paginate: 3
#paginate_path: "/news/page:num/"
baseurl: "/"
# Build settings
#theme: minima
#plugins:
#- jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
